# Generated by Django 6.1 on 2026-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        ("users", "0006_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для перехода на оплату в Stripe",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии в Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("card", "Банковская карта"),
                ],
                help_text="Выберите способ оплаты",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course")},
        ),
    ]
