# Generated by Django 6.1 on 2026-09-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payments_payment_url_payments_stripe_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка для перехода на оплату в Stripe",
                max_length=700,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
